package edu.illinois.ncsa.mmdb.web.server.rest;

import java.io.File;
import java.util.logging.Level;

import org.restlet.Application;
import org.restlet.Component;
import org.restlet.Restlet;
import org.restlet.data.LocalReference;
import org.restlet.data.Protocol;
import org.restlet.resource.Directory;
import org.restlet.routing.Router;

public class MediciServerApplication extends Application {
    /**
     * When launched as a standalone application.
     * 
     * @param args
     * @throws Exception
     */
    public static void main(String[] args) throws Exception {
        Component component = new Component();
        component.getClients().add(Protocol.FILE);
        component.getServers().add(Protocol.HTTP, 8080);
        component.getDefaultHost().attach(new MediciServerApplication());
        component.start();
    }

    @Override
    public Restlet createInboundRoot() {
        getLogger().setLevel(Level.WARNING);
        Router router = new Router(getContext());
        getConnectorService().getClientProtocols().add(Protocol.FILE);

        // Serve the files generated by the GWT compilation step.
        File warDir = new File("").getAbsoluteFile();
        if (!"war".equals(warDir.getName())) {
            warDir = new File(warDir, "war/");
        }
        System.out.println(warDir.getAbsoluteFile());
        Directory dir = new Directory(getContext(), LocalReference.createFileReference(warDir));
        dir.getLogger().setLevel(Level.WARNING);
        router.attachDefault(dir);

        // ----------------------------------------------------------------------
        // ImagePyramid
        // ----------------------------------------------------------------------
        router.attach("/pyramid/{dataset}/xml", ImagePyramidResource.class); //$NON-NLS-1$
        router.attach("/pyramid/{dataset}/xml_files/{level}/{col}_{row}.{ext}", ImagePyramidTileResource.class); //$NON-NLS-1$

        return router;
    }
}
